# Generated by Django 2.1.3 on 2018-11-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Модель ноутбука')),
                ('brand', models.CharField(max_length=255, verbose_name='Бренд ')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Диагональ ')),
                ('oper_system', models.CharField(choices=[('mac', 'MacOS'), ('linux', 'Linux'), ('windows', 'Windows')], max_length=255, verbose_name='Операционная система')),
                ('oper_memory', models.IntegerField(verbose_name='ОЗУ')),
                ('type_monitor', models.CharField(choices=[('glossy', 'Глянцевый'), ('matt', 'Матовый')], max_length=255, verbose_name='Тип экрана')),
                ('count_core', models.IntegerField(verbose_name='Количество ядер')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
        ),
    ]
