# Generated by Django 2.1.3 on 2018-11-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='brand',
            field=models.CharField(default='Apple', max_length=255, verbose_name='Бренд '),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='count_core',
            field=models.IntegerField(default=8, verbose_name='Количество ядер'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='diagonal',
            field=models.CharField(default='12', max_length=255, verbose_name='Диагональ '),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='model',
            field=models.CharField(default='i534', max_length=255, verbose_name='Модель ноутбука'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='oper_memory',
            field=models.IntegerField(default=16, verbose_name='ОЗУ'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='price',
            field=models.IntegerField(default='50000', verbose_name='Цена'),
        ),
    ]
