# Generated by Django 2.1.3 on 2018-11-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20181104_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Картинка'),
        ),
    ]
