# Generated by Django 2.1.3 on 2018-11-05 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_auto_20181105_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.Category'),
        ),
    ]
