# Generated by Django 2.1.3 on 2018-11-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_auto_20181105_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('laptops', 'Ноутбуки'), ('mobile_phones', 'Телефоны'), ('tablet', 'Планшеты'), ('source_details', 'Комплектующие'), ('nau', 'Наушники')], max_length=100, verbose_name='Категория'),
        ),
    ]
